packages:
  - 'apps/*'
allowBuilds:
  bcrypt: true
  better-sqlite3: true
  sqlite3: true
  unrs-resolver: true
  esbuild: true
overrides:
  raw-body@3: 4.0.0
  webpack@<=5.107.2: 5.107.2
  yargs@17: 18.1.0
